env:
  global:
    - CC_TEST_REPORTER_ID=1a841bb9ff060eceaf86ceee385f89f73b371252b737cf1329b950c22186476d

language: python
python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - pip install poetry
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - make install

script:
  - make check

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
